version: '3'
services:

  mariadb:
    image: mariadb:10.3
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: glastonbury
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  zookeeper:
    image: zookeeper:3.4.13
    ports:
      - "2181:2181"
      - "2888"

  kafka:
    image: wurstmeister/kafka:2.12-2.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
