DROP TABLE IF EXISTS invetory;
DROP TABLE IF EXISTS reserve;

CREATE TABLE invetory (
  ID VARCHAR(250)  PRIMARY KEY,
  FESTIVAL_NAME VARCHAR(250) NOT NULL,
  QTY_AVAILABLE INT NOT NULL,
);

CREATE TABLE reserve (
  id  VARCHAR(250)  PRIMARY KEY,
  ORDER_ID VARCHAR(250) NOT NULL,
  CUSTOMER_ID VARCHAR(250) NOT NULL,
  INVENTORY_ID VARCHAR(250)  NOT NULL,
  AMOUNT DECIMAL NOT NULL,
  FOREIGN KEY (INVENTORY_ID) REFERENCES invetory(ID),
  );

INSERT INTO invetory (id, FESTIVAL_NAME, QTY_AVAILABLE) VALUES
  ('3852cb18-9c19-4326-ac77-a1a0264bd98c', 'glastonbury', 100);

